// 마스코트 "구름이" — 픽셀 도트 클라우드. 디자인 시안(기분이.dc)에서 이식.
// 기분 = 날씨: 행복(해)·설렘(반짝)·평온(산들)·우울(비)·화남(번개).
// mascotSVG(mood, plain): plain=true면 날씨 이펙트 없이(작은 버튼·그리드용).
// 애니메이션 키프레임 gi-* 는 css/styles.css 에 정의.

const BODY = {
  happy: `<g fill="#FFC95C"><rect x="4" y="0" width="3" height="1"/><rect x="8" y="0" width="3" height="1"/><rect x="12" y="0" width="3" height="1"/><rect x="3" y="1" width="13" height="1"/><rect x="2" y="2" width="15" height="1"/><rect x="1" y="3" width="17" height="1"/><rect x="0" y="4" width="19" height="2"/><rect x="1" y="6" width="17" height="1"/><rect x="3" y="7" width="13" height="1"/><rect x="5" y="8" width="9" height="1"/></g><g fill="#FFC95C" opacity=".5"><rect x="4" y="0" width="1" height="1"/><rect x="14" y="0" width="1" height="1"/><rect x="0" y="3" width="1" height="1"/><rect x="18" y="3" width="1" height="1"/><rect x="4" y="8" width="1" height="1"/><rect x="13" y="8" width="1" height="1"/></g><g fill="#FFF2C8" opacity=".9"><rect x="3" y="1" width="3" height="1"/><rect x="2" y="2" width="2" height="1"/></g><g fill="#E0A93B" opacity=".3"><rect x="3" y="7" width="13" height="1"/></g><g fill="#E0A93B"><rect x="6" y="9" width="2" height="3" style="animation:gi-legL 1.3s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:center top"/><rect x="11" y="9" width="2" height="3" style="animation:gi-legR 1.3s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:center top"/></g><rect x="3" y="6" width="2" height="1" fill="#FF6F50" opacity=".5"/><rect x="14" y="6" width="2" height="1" fill="#FF6F50" opacity=".5"/><g style="animation:gi-blink2 4.6s infinite;transform-box:fill-box;transform-origin:center"><rect x="6" y="4" width="2" height="2" fill="#2A2520"/><rect x="11" y="4" width="2" height="2" fill="#2A2520"/><rect x="6" y="4" width="1" height="1" fill="#fff"/><rect x="11" y="4" width="1" height="1" fill="#fff"/></g><g fill="#2A2520"><rect x="7" y="6" width="1" height="1"/><rect x="11" y="6" width="1" height="1"/><rect x="8" y="7" width="3" height="1"/></g>`,
  flutter: `<g fill="#FF9A8B"><rect x="4" y="0" width="3" height="1"/><rect x="8" y="0" width="3" height="1"/><rect x="12" y="0" width="3" height="1"/><rect x="3" y="1" width="13" height="1"/><rect x="2" y="2" width="15" height="1"/><rect x="1" y="3" width="17" height="1"/><rect x="0" y="4" width="19" height="2"/><rect x="1" y="6" width="17" height="1"/><rect x="3" y="7" width="13" height="1"/><rect x="5" y="8" width="9" height="1"/></g><g fill="#FF9A8B" opacity=".5"><rect x="4" y="0" width="1" height="1"/><rect x="14" y="0" width="1" height="1"/><rect x="0" y="3" width="1" height="1"/><rect x="18" y="3" width="1" height="1"/><rect x="4" y="8" width="1" height="1"/><rect x="13" y="8" width="1" height="1"/></g><g fill="#FFE0D8" opacity=".9"><rect x="3" y="1" width="3" height="1"/><rect x="2" y="2" width="2" height="1"/></g><g fill="#E07F6F" opacity=".3"><rect x="3" y="7" width="13" height="1"/></g><g fill="#E07F6F"><rect x="6" y="9" width="2" height="3" style="animation:gi-legL 1s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:center top"/><rect x="11" y="9" width="2" height="3" style="animation:gi-legR 1s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:center top"/></g><rect x="3" y="6" width="2" height="1" fill="#FF6F50" opacity=".75"/><rect x="14" y="6" width="2" height="1" fill="#FF6F50" opacity=".75"/><g style="animation:gi-blink 3.4s infinite;transform-box:fill-box;transform-origin:center"><rect x="6" y="4" width="2" height="2" fill="#2A2520"/><rect x="11" y="4" width="2" height="2" fill="#2A2520"/><rect x="6" y="4" width="1" height="1" fill="#fff"/><rect x="11" y="4" width="1" height="1" fill="#fff"/></g><rect x="8" y="6" width="2" height="2" fill="#2A2520"/>`,
  calm: `<g fill="#9CC3A6"><rect x="4" y="0" width="3" height="1"/><rect x="8" y="0" width="3" height="1"/><rect x="12" y="0" width="3" height="1"/><rect x="3" y="1" width="13" height="1"/><rect x="2" y="2" width="15" height="1"/><rect x="1" y="3" width="17" height="1"/><rect x="0" y="4" width="19" height="2"/><rect x="1" y="6" width="17" height="1"/><rect x="3" y="7" width="13" height="1"/><rect x="5" y="8" width="9" height="1"/></g><g fill="#9CC3A6" opacity=".5"><rect x="4" y="0" width="1" height="1"/><rect x="14" y="0" width="1" height="1"/><rect x="0" y="3" width="1" height="1"/><rect x="18" y="3" width="1" height="1"/><rect x="4" y="8" width="1" height="1"/><rect x="13" y="8" width="1" height="1"/></g><g fill="#E9F3EC" opacity=".9"><rect x="3" y="1" width="3" height="1"/><rect x="2" y="2" width="2" height="1"/></g><g fill="#6E9C79" opacity=".25"><rect x="3" y="7" width="13" height="1"/></g><g fill="#6E9C79"><rect x="6" y="9" width="2" height="3" style="animation:gi-legL 1.8s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:center top"/><rect x="11" y="9" width="2" height="3" style="animation:gi-legR 1.8s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:center top"/></g><rect x="3" y="6" width="2" height="1" fill="#FF6F50" opacity=".4"/><rect x="14" y="6" width="2" height="1" fill="#FF6F50" opacity=".4"/><g fill="#2A2520"><rect x="6" y="5" width="2" height="1"/><rect x="11" y="5" width="2" height="1"/><rect x="7" y="6" width="1" height="1"/><rect x="11" y="6" width="1" height="1"/><rect x="8" y="7" width="3" height="1"/></g>`,
  blue: `<g fill="#8AA0C9"><rect x="4" y="0" width="3" height="1"/><rect x="8" y="0" width="3" height="1"/><rect x="12" y="0" width="3" height="1"/><rect x="3" y="1" width="13" height="1"/><rect x="2" y="2" width="15" height="1"/><rect x="1" y="3" width="17" height="1"/><rect x="0" y="4" width="19" height="2"/><rect x="1" y="6" width="17" height="1"/><rect x="3" y="7" width="13" height="1"/><rect x="5" y="8" width="9" height="1"/></g><g fill="#8AA0C9" opacity=".5"><rect x="4" y="0" width="1" height="1"/><rect x="14" y="0" width="1" height="1"/><rect x="0" y="3" width="1" height="1"/><rect x="18" y="3" width="1" height="1"/><rect x="4" y="8" width="1" height="1"/><rect x="13" y="8" width="1" height="1"/></g><g fill="#EAF0FA" opacity=".85"><rect x="3" y="1" width="3" height="1"/><rect x="2" y="2" width="2" height="1"/></g><g fill="#5C719E" opacity=".3"><rect x="3" y="7" width="13" height="1"/></g><g fill="#5C719E"><rect x="6" y="9" width="2" height="3"/><rect x="11" y="9" width="2" height="3"/></g><g fill="#2A2520"><rect x="6" y="3" width="2" height="1"/><rect x="11" y="3" width="2" height="1"/></g><g style="animation:gi-blinkSlow 5.4s infinite;transform-box:fill-box;transform-origin:center"><rect x="6" y="4" width="2" height="2" fill="#2A2520"/><rect x="11" y="4" width="2" height="2" fill="#2A2520"/></g><g fill="#2A2520"><rect x="7" y="7" width="1" height="1"/><rect x="11" y="7" width="1" height="1"/><rect x="8" y="6" width="3" height="1"/></g>`,
  angry: `<g fill="#E2725B"><rect x="4" y="0" width="3" height="1"/><rect x="8" y="0" width="3" height="1"/><rect x="12" y="0" width="3" height="1"/><rect x="3" y="1" width="13" height="1"/><rect x="2" y="2" width="15" height="1"/><rect x="1" y="3" width="17" height="1"/><rect x="0" y="4" width="19" height="2"/><rect x="1" y="6" width="17" height="1"/><rect x="3" y="7" width="13" height="1"/><rect x="5" y="8" width="9" height="1"/></g><g fill="#E2725B" opacity=".5"><rect x="4" y="0" width="1" height="1"/><rect x="14" y="0" width="1" height="1"/><rect x="0" y="3" width="1" height="1"/><rect x="18" y="3" width="1" height="1"/><rect x="4" y="8" width="1" height="1"/><rect x="13" y="8" width="1" height="1"/></g><g fill="#F0D8D0" opacity=".7"><rect x="3" y="1" width="3" height="1"/><rect x="2" y="2" width="2" height="1"/></g><g fill="#962F1F" opacity=".3"><rect x="3" y="7" width="13" height="1"/></g><g fill="#962F1F"><rect x="6" y="9" width="2" height="3"/><rect x="11" y="9" width="2" height="3"/></g><g fill="#2A2520"><rect x="6" y="3" width="1" height="1"/><rect x="7" y="4" width="1" height="1"/><rect x="12" y="3" width="1" height="1"/><rect x="11" y="4" width="1" height="1"/></g><g style="animation:gi-blink 4.7s infinite;transform-box:fill-box;transform-origin:center"><rect x="6" y="5" width="2" height="2" fill="#2A2520"/><rect x="11" y="5" width="2" height="2" fill="#2A2520"/></g><g fill="#2A2520"><rect x="7" y="8" width="1" height="1"/><rect x="11" y="8" width="1" height="1"/><rect x="8" y="7" width="3" height="1"/></g>`,
};

const W_BACK = {
  happy: `<g style="animation:gi-spin 16s linear infinite;transform-box:fill-box;transform-origin:center"><g fill="#FFC24D" style="animation:gi-pulse 3s ease-in-out infinite;transform-box:fill-box;transform-origin:center"><rect x="17" y="-5" width="3" height="3"/><rect x="16" y="-3" width="1" height="1"/><rect x="20" y="-3" width="1" height="1"/><rect x="18" y="-7" width="1" height="1"/><rect x="18" y="-1" width="1" height="1"/><rect x="21" y="-1" width="1" height="1"/></g></g>`,
};
const W_FRONT = {
  flutter: `<g fill="#FF6F50"><g style="animation:gi-twinkle 1.7s ease-in-out infinite;transform-box:fill-box;transform-origin:center"><rect x="-1" y="-4" width="1" height="3"/><rect x="-2" y="-3" width="3" height="1"/></g><g style="animation:gi-twinkle 1.7s ease-in-out .6s infinite;transform-box:fill-box;transform-origin:center"><rect x="20" y="-5" width="1" height="3"/><rect x="19" y="-4" width="3" height="1"/></g><g style="animation:gi-twinkle 1.7s ease-in-out 1.1s infinite;transform-box:fill-box;transform-origin:center"><rect x="20" y="6" width="1" height="3"/><rect x="19" y="7" width="3" height="1"/></g></g>`,
  calm: `<g fill="#9CC3A6"><g style="animation:gi-drift 3.6s ease-in-out infinite"><rect x="-2" y="4" width="3" height="1"/></g><g style="animation:gi-drift 3.6s ease-in-out 1.8s infinite"><rect x="-2" y="7" width="2" height="1"/></g></g>`,
  blue: `<g fill="#7E95C2"><rect x="6" y="12" width="1" height="2" style="animation:gi-rain 1.3s cubic-bezier(.45,.05,.55,.95) infinite"/><rect x="9" y="12" width="1" height="2" style="animation:gi-rain 1.3s cubic-bezier(.45,.05,.55,.95) .5s infinite"/><rect x="12" y="12" width="1" height="2" style="animation:gi-rain 1.3s cubic-bezier(.45,.05,.55,.95) .9s infinite"/></g>`,
  angry: `<rect x="7" y="12" width="5" height="3" rx="1" fill="#FFC24D" opacity=".25" style="animation:gi-glow 1.4s ease-in-out infinite;transform-box:fill-box;transform-origin:center"/><g fill="#FFC24D" style="animation:gi-flash 1.4s ease-in-out infinite"><rect x="9" y="11" width="1" height="2"/><rect x="8" y="13" width="2" height="1"/><rect x="7" y="13" width="1" height="2"/></g>`,
};

export function mascotSVG(mood = 'happy', plain = false) {
  const body = BODY[mood] || BODY.happy;
  const wb = plain ? '' : (W_BACK[mood] || '');
  const wf = plain ? '' : (W_FRONT[mood] || '');
  return `<svg class="gi" viewBox="-3 -7 25 23" preserveAspectRatio="xMidYMid meet" shape-rendering="crispEdges" style="overflow:visible;display:block;width:100%;height:100%">`
    + `<g style="animation:gi-bob 5s cubic-bezier(.45,.05,.55,.95) infinite"><g style="animation:gi-sway 7s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:50% 90%"><g style="animation:gi-breathe 4.4s cubic-bezier(.45,.05,.55,.95) infinite;transform-box:fill-box;transform-origin:50% 90%">`
    + `${wb}${body}${wf}</g></g></g></svg>`;
}
