/**
 * 카오모지 확장 라이브러리 — 외부 공개 데이터셋(빌드 시 1회 가공·정적 임베드).
 * 런타임 fetch 없음(서버 0·비용 0). 영문 keywords로도 검색된다.
 *
 * 출처(둘 다 MIT 라이선스, 저작권 표기 보존):
 *  - asciilib © Ian Sinnott (https://github.com/iansinnott/asciilib) — MIT
 *  - kaomojiLib © icyCake (https://github.com/Yuuki221/kaomojiLib) — MIT
 * 카오모지(텍스트 이모티콘) 자체는 표준 유니코드 문자열로 저작권 대상이 아님.
 */
export interface LibraryItem { text: string; emotion: string; keywords: string[]; }

export const LIBRARY: LibraryItem[] = [
  {"text": "( ͜。 ͡ʖ ͜。)","emotion": "play","keywords": ["upside","down","lenny"]},
  {"text": "( ͡° ͜ʖ ͡°)","emotion": "play","keywords": ["lenny"]},
  {"text": "Σ_(꒪ཀ꒪」∠)_","emotion": "play","keywords": ["fungry"]},
  {"text": "ヽ（´ー｀）┌","emotion": "play","keywords": ["drunkenness"]},
  {"text": "ヘ（。□°）ヘ","emotion": "play","keywords": ["derp"]},
  {"text": "ヽ(⌐■_■)ノ♪♬","emotion": "play","keywords": ["jazz","musician"]},
  {"text": "(/・・)ノ","emotion": "play","keywords": ["dance"]},
  {"text": "( •_•)>⌐■-■ (⌐■_■)","emotion": "play","keywords": ["deal","with","it"]},
  {"text": "((ヽ(๑╹◡╹๑)ﾉ))♬","emotion": "play","keywords": ["music","sing","party","relax"]},
  {"text": "C= C= C= C=┌(｀ー´)┘","emotion": "play","keywords": ["run","escape","right"]},
  {"text": "٩(๑･ิᴗ･ิ)۶٩(･ิᴗ･ิ๑)۶","emotion": "play","keywords": ["friends","hangout","play","party"]},
  {"text": "(ﾉ･ｪ･)ﾉ","emotion": "play","keywords": ["excited","dance"]},
  {"text": "(*ﾉ・ω・)ﾉ♫♩ヽ(・ω・ヽ*)♬ヽ(*・ω・)ﾉ","emotion": "play","keywords": ["excited","dance","sing"]},
  {"text": "♫ヽ(゜∇゜ヽ)♪♬(ノ゜∇゜)ノ♩♪","emotion": "play","keywords": ["excited","dance","sing"]},
  {"text": "♬♩♪♩( ◜◒◝ )♩♪♩♬","emotion": "play","keywords": ["excited","dance","sing"]},
  {"text": "♪♪♪ ヽ(･ˇ∀ˇ･ゞ)","emotion": "play","keywords": ["excited","dance","sing"]},
  {"text": "(* >ω<)","emotion": "play","keywords": ["excited"]},
  {"text": "(ﾉ≧∀≦)ﾉ","emotion": "play","keywords": ["excited","dance"]},
  {"text": "(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧","emotion": "play","keywords": ["excited"]},
  {"text": "\\( ‘з’)/","emotion": "play","keywords": ["excited"]},
  {"text": "＼（＾▽＾）／","emotion": "play","keywords": ["excited"]},
  {"text": "ヽ( ★ω★)ノ","emotion": "play","keywords": ["excited"]},
  {"text": "ヾ(。◕ฺ∀◕ฺ)ノ","emotion": "play","keywords": ["excited"]},
  {"text": "ヽ(=^･ω･^=)丿","emotion": "play","keywords": ["excited","cat"]},
  {"text": "٩(^ᴗ^)۶","emotion": "play","keywords": ["excited"]},
  {"text": "(๑>ᴗ<๑)","emotion": "play","keywords": ["excited"]},
  {"text": "٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ","emotion": "play","keywords": ["excited"]},
  {"text": "୧(﹒︠ᴗ﹒︡)୨","emotion": "play","keywords": ["excited"]},
  {"text": "˚₊*(ˊॢo̶̶̷̤◡ुo̴̶̷̤ˋॢ)*₊˚⁎","emotion": "play","keywords": ["excited"]},
  {"text": "•ू(ᵒ̴̶̷ωᵒ̴̶̷*•ू) ​ )੭ु⁾","emotion": "play","keywords": ["excited"]},
  {"text": "(❛ัॢᵕ❛ั ॢ)✩*ೃ.⋆","emotion": "play","keywords": ["excited","think"]},
  {"text": "⁺✧.(˃̶ ॣ⌣ ॣ˂̶∗̀)ɞ⁾","emotion": "play","keywords": ["excited"]},
  {"text": "٩(●˙▿˙●)۶…⋆ฺ","emotion": "play","keywords": ["excited"]},
  {"text": "*✲ﾟ*｡✧٩(･ิᴗ･ิ๑)۶*✲ﾟ*｡✧","emotion": "play","keywords": ["excited"]},
  {"text": "( ˃̶ω˂̶ ૃ)","emotion": "play","keywords": ["excited"]},
  {"text": "૮(ᶿ̴͈᷇ॢ௰ᶿ̴͈᷆ॢ)ა✧","emotion": "play","keywords": ["excited"]},
  {"text": "␟␏(ɲ˃ ˈ̫̮ ˂ɳ)␟␏ෆ","emotion": "play","keywords": ["excited"]},
  {"text": "ε=(っ≧ω≦)っ","emotion": "play","keywords": ["run"]},
  {"text": "ミヽ（。＞＜）ノ","emotion": "play","keywords": ["run"]},
  {"text": "ε=┌(;･_･)┘","emotion": "play","keywords": ["run"]},
  {"text": "ヽ(。_°)ノ","emotion": "play","keywords": ["whatever","crazy","shrug"]},
  {"text": "¯\\(°_o)/¯","emotion": "play","keywords": ["whatever","crazy","shrug"]},
  {"text": "(。ヘ°)","emotion": "play","keywords": ["confused","crazy"]},
  {"text": "(⊙_◎)","emotion": "play","keywords": ["confused","crazy"]},
  {"text": "⁀⊙﹏☉⁀","emotion": "play","keywords": ["confused","crazy"]},
  {"text": "(♠_♦)","emotion": "play","keywords": ["confused","crazy"]},
  {"text": "`(๑ △ ๑)`*","emotion": "play","keywords": ["confused","crazy"]},
  {"text": "ヽ(^‥^=ゞ)","emotion": "play","keywords": ["cat","dance"]},
  {"text": "└(=^‥^=)┐","emotion": "play","keywords": ["cat","dance"]},
  {"text": "(☉ε ⊙ﾉ)ﾉ","emotion": "play","keywords": ["crazy"]},
  {"text": "＼(●o○;)ノ","emotion": "play","keywords": ["crazy"]},
  {"text": "~(๑ñ﹏ ⊙☆)ノ","emotion": "play","keywords": ["crazy"]},
  {"text": "ヾ (✿＞﹏ ⊙〃)ノ","emotion": "play","keywords": ["crazy"]},
  {"text": "ヽ(｡ゝω・｡)ﾉ","emotion": "play","keywords": ["crazy"]},
  {"text": "ヾ(｡ꏿ﹏ꏿ)ﾉﾞ","emotion": "play","keywords": ["crazy"]},
  {"text": "ヽ(゜Q。)ノ","emotion": "play","keywords": ["crazy"]},
  {"text": "Σ(♡＠﹏ ＠☆)ﾉ”","emotion": "play","keywords": ["crazy"]},
  {"text": "щ (*ㅇ△ Φ☆)ノ","emotion": "play","keywords": ["crazy"]},
  {"text": "ヘ（゜◇、゜）ノ","emotion": "play","keywords": ["crazy"]},
  {"text": "( ख़ืིڞ◟྄ख़ืི)","emotion": "play","keywords": ["crazy"]},
  {"text": "< ( o ) > </ ( o ) >","emotion": "blank","keywords": ["code","eyes","face"]},
  {"text": ": ◉ ∧ ◉ : ╏","emotion": "blank","keywords": ["blank"]},
  {"text": "¿ⓧ_ⓧﮌ","emotion": "blank","keywords": ["dead","eyes"]},
  {"text": "[¬º-°]¬","emotion": "blank","keywords": ["zombie"]},
  {"text": "(>ლ)","emotion": "blank","keywords": ["face","palm"]},
  {"text": "__φ(．．)","emotion": "blank","keywords": ["writing","study","essay","working hard"]},
  {"text": "＿φ( °-°)/","emotion": "blank","keywords": ["write"]},
  {"text": "＿φ(°-°=)","emotion": "blank","keywords": ["write"]},
  {"text": "φ(．．;)","emotion": "blank","keywords": ["write"]},
  {"text": "φ(^∇^ )","emotion": "blank","keywords": ["write"]},
  {"text": "φ(◎◎ヘ)","emotion": "blank","keywords": ["write"]},
  {"text": "ψ(。。)","emotion": "blank","keywords": ["write"]},
  {"text": "___ψ(‥ )","emotion": "blank","keywords": ["write"]},
  {"text": "＿φ(￣ー￣ )","emotion": "blank","keywords": ["write"]},
  {"text": "ණ⃛(ᵒ͈̑ᴗ̂ᵒ͈̑ )”","emotion": "blank","keywords": ["write"]},
  {"text": "＿〆(。。)","emotion": "blank","keywords": ["write"]},
  {"text": "(‘•̀ ▽ •́ )φ","emotion": "blank","keywords": ["write"]},
  {"text": "φ(・ω・｀ )","emotion": "blank","keywords": ["write"]},
  {"text": "φ(._.)","emotion": "blank","keywords": ["write"]},
  {"text": "φ（．．）","emotion": "blank","keywords": ["write"]},
  {"text": "φ(￣ー￣ )ノ","emotion": "blank","keywords": ["write"]},
  {"text": "φ(°ρ°*)メ","emotion": "blank","keywords": ["write"]},
  {"text": "〆(・∀・＠)","emotion": "blank","keywords": ["write"]},
  {"text": "〆(´Ｕ_｀*)","emotion": "blank","keywords": ["write"]},
  {"text": "φ(^ω^*)ﾉ","emotion": "blank","keywords": ["write"]},
  {"text": "…φ(o´ωﾟo)φ…","emotion": "blank","keywords": ["write"]},
  {"text": "σ(ൈ)φ","emotion": "blank","keywords": ["write"]},
  {"text": "໒(⊙ᴗ⊙)७✎▤","emotion": "blank","keywords": ["write"]},
  {"text": "[≡] 〆(・⺫・‶)","emotion": "blank","keywords": ["write"]},
  {"text": "(๑╹o╹)φ","emotion": "blank","keywords": ["write"]},
  {"text": "†=”Ⴛ̸ ♡(˃͈ દ ˂͈ ༶ )","emotion": "blank","keywords": ["write"]},
  {"text": "(✖╭╮✖)","emotion": "blank","keywords": ["dead"]},
  {"text": "(u_u)","emotion": "blank","keywords": ["dead"]},
  {"text": "(*_*)","emotion": "blank","keywords": ["dead"]},
  {"text": "(＊0＊;)","emotion": "blank","keywords": ["dead"]},
  {"text": "(+_+)","emotion": "blank","keywords": ["dead"]},
  {"text": "(×_×;）","emotion": "blank","keywords": ["dead"]},
  {"text": "(ñ_ñ)","emotion": "blank","keywords": ["dead"]},
  {"text": "(o_-)","emotion": "blank","keywords": ["dead"]},
  {"text": "(º_º)","emotion": "blank","keywords": ["dead"]},
  {"text": "（x_x；）","emotion": "blank","keywords": ["dead"]},
  {"text": "（Ω_Ω）","emotion": "blank","keywords": ["dead"]},
  {"text": "✘Д✘◍","emotion": "blank","keywords": ["dead"]},
  {"text": "ヾ(×× ) ﾂ","emotion": "blank","keywords": ["dead"]},
  {"text": "٩(×̯×)۶","emotion": "blank","keywords": ["dead"]},
  {"text": "Σ(๑+⌓ o｡)シ","emotion": "blank","keywords": ["dead"]},
  {"text": "へ（>_<へ)","emotion": "blank","keywords": ["dead"]},
  {"text": "(｡´✚ฺω✚ฺ｀｡)","emotion": "blank","keywords": ["dead"]},
  {"text": "(｡≍ฺ‿ฺ≍ฺ)","emotion": "blank","keywords": ["dead"]},
  {"text": "╭( ✖_✖ )╮","emotion": "blank","keywords": ["dead"]},
  {"text": "―(T_T)→","emotion": "blank","keywords": ["dead"]},
  {"text": "\\ō͡≡o˞̶","emotion": "embarrassed","keywords": ["race","car"]},
  {"text": "_:(´□`」 ∠):_","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "╰╏ ◉ 〜 ◉ ╏╯","emotion": "embarrassed","keywords": ["almost","cared"]},
  {"text": "( ﾟ Дﾟ)","emotion": "embarrassed","keywords": ["afraid"]},
  {"text": "(*´ڡ`●)","emotion": "embarrassed","keywords": ["delicious","yummy","food","eat"]},
  {"text": "m(_ _;m)","emotion": "embarrassed","keywords": ["sorry","i am wrong","confess"]},
  {"text": "(^_^;)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(^^ゞ","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(^^;)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(‘-’*)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*^^*)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(⌒_⌒;)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "（*/∇＼*）","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(〃￣ω￣〃ゞ","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*´ｪ｀*)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*´∀`*)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*´_ゝ｀)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(/ω＼)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*ﾉ▽ﾉ)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*ﾉωﾉ)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "（/｡＼)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "（。-＿-。）","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(╯_╰)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(╯ಊ╰)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(ﾉ)´∀｀(ヾ)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*/ω＼*)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "\\(//∇//)\\","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(*ﾟｰﾟ)ゞ","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "\\(///Σ///)\\","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "（//･_･//)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(⊙﹏⊙✿)","emotion": "embarrassed","keywords": ["embarassed","crazy"]},
  {"text": "(<o///v>)","emotion": "embarrassed","keywords": ["embarassed"]},
  {"text": "(ノдヽ)","emotion": "embarrassed","keywords": ["scared"]},
  {"text": "ヽ(ﾟДﾟ)ﾉ","emotion": "embarrassed","keywords": ["scared"]},
  {"text": "(／。＼)","emotion": "embarrassed","keywords": ["scared"]},
  {"text": "（／_＼）","emotion": "embarrassed","keywords": ["scared"]},
  {"text": "（／．＼）","emotion": "embarrassed","keywords": ["scared"]},
  {"text": "m(￢0￢)m","emotion": "embarrassed","keywords": ["think","sorry"]},
  {"text": "ｍ（＿ ＿；；ｍ","emotion": "embarrassed","keywords": ["sorry","dead"]},
  {"text": "(シ_ _)シ","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "（ﾉ´д｀）","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "<(_ _)>","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "＜(。_。)＞","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "m(_ _)m","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "m(._.)m","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "ｍ（．＿．）ｍ","emotion": "embarrassed","keywords": ["sorry"]},
  {"text": "(￣(エ)￣)","emotion": "cute","keywords": ["bear"]},
  {"text": "ʕ·͡ᴥ·ʔ","emotion": "cute","keywords": ["polar","bear"]},
  {"text": "-^^,--,~","emotion": "cute","keywords": ["fox"]},
  {"text": "-=iii=<()","emotion": "cute","keywords": ["trumpet"]},
  {"text": "ʕつ•ᴥ•ʔつ","emotion": "cute","keywords": ["bear","with","outstretched","arms"]},
  {"text": "ʕ⌐■ᴥ■ʔ","emotion": "cute","keywords": ["bear","with","glasses"]},
  {"text": "ʕಠಿᴥಠʔ","emotion": "cute","keywords": ["bear","with","doubting","eyes"]},
  {"text": "ʕつ ͡°ᴥ ͡°ʔつ","emotion": "cute","keywords": ["creep","bear","with","outstretched","arms"]},
  {"text": "~(^._.)","emotion": "cute","keywords": ["round","cat"]},
  {"text": ",(u°)>","emotion": "cute","keywords": ["round","bird"]},
  {"text": "><((((`>","emotion": "cute","keywords": ["fish"]},
  {"text": "( ´(00)`)","emotion": "cute","keywords": ["pig"]},
  {"text": "----{,_,\">","emotion": "cute","keywords": ["mouse"]},
  {"text": "=^..^=","emotion": "cute","keywords": ["kitty","cat"]},
  {"text": "(,(,(,(,(,(,(,(, \")","emotion": "cute","keywords": ["caterpillar"]},
  {"text": "ヽ(￣(ｴ)￣)ﾉ","emotion": "cute","keywords": ["panda"]},
  {"text": "(∩◕(oo)◕∩)","emotion": "cute","keywords": ["piggy"]},
  {"text": "（・⊝・）","emotion": "cute","keywords": ["bird"]},
  {"text": "ʕ •ᴥ• ʔ","emotion": "cute","keywords": ["bear","polar bear","smile bear"]},
  {"text": "∪･ω･∪","emotion": "cute","keywords": ["dog","dog ear down"]},
  {"text": "／(≧ x ≦)＼","emotion": "cute","keywords": ["rabbit","exciting","joy"]},
  {"text": "(◉Θ◉)","emotion": "cute","keywords": ["bird","black round eyes","fly"]},
  {"text": "▼・ᴥ・▼","emotion": "cute","keywords": ["dog","animal","bark","pet"]},
  {"text": "=^._.^= ∫","emotion": "cute","keywords": ["cat","animal","nya","meow","simple","pet"]},
  {"text": "（・⊝・∞）","emotion": "cute","keywords": ["bird"]},
  {"text": "（・θ・）","emotion": "cute","keywords": ["bird"]},
  {"text": "（＠◇＠）","emotion": "cute","keywords": ["bird"]},
  {"text": "(•∋•)","emotion": "cute","keywords": ["bird"]},
  {"text": "（`･⊝･´ ）","emotion": "cute","keywords": ["bird"]},
  {"text": "(`･⊝･´)","emotion": "cute","keywords": ["bird"]},
  {"text": "(｀Θ´)","emotion": "cute","keywords": ["bird"]},
  {"text": "(°<°)","emotion": "cute","keywords": ["bird"]},
  {"text": "（ﾟ∈ﾟ）","emotion": "cute","keywords": ["bird"]},
  {"text": "(●∈∋●)","emotion": "cute","keywords": ["bird"]},
  {"text": "<（ё）>","emotion": "cute","keywords": ["bird"]},
  {"text": "~~……ヾლ∩з…….~~","emotion": "cute","keywords": ["bird"]},
  {"text": "⊹⋛⋋( ՞ਊ ՞)⋌⋚⊹","emotion": "cute","keywords": ["bird"]},
  {"text": "◎▼◎","emotion": "cute","keywords": ["bird"]},
  {"text": "ˏ₍•ɞ•₎ˎ","emotion": "cute","keywords": ["bird"]},
  {"text": "ˎ₍•ʚ•₎ˏ","emotion": "cute","keywords": ["bird"]},
  {"text": "꜀( ˊ̠˂˃ˋ̠ )꜆","emotion": "cute","keywords": ["bird"]},
  {"text": "ꉂ (๑¯ਊ¯)σ","emotion": "cute","keywords": ["bird"]},
  {"text": "(=^･ｪ･^=)","emotion": "cute","keywords": ["cat"]},
  {"text": "(=^‥^=)","emotion": "cute","keywords": ["cat"]},
  {"text": "(=^･^=)","emotion": "cute","keywords": ["cat"]},
  {"text": "V(=^･ω･^=)v","emotion": "cute","keywords": ["cat"]},
  {"text": "(=｀ω´=)","emotion": "cute","keywords": ["cat"]},
  {"text": "o(^・x・^)o","emotion": "cute","keywords": ["cat"]},
  {"text": "＼(=^‥^)/’`","emotion": "cute","keywords": ["cat"]},
  {"text": "( =①ω①=)","emotion": "cute","keywords": ["cat"]},
  {"text": "d(=^･ω･^=)b","emotion": "cute","keywords": ["cat"]},
  {"text": "(=ＴェＴ=)","emotion": "cute","keywords": ["cat"]},
  {"text": "(=;ェ;=)","emotion": "cute","keywords": ["cat"]},
  {"text": "(=^･ω･^)y＝","emotion": "cute","keywords": ["cat"]},
  {"text": "(^-人-^)","emotion": "cute","keywords": ["cat"]},
  {"text": "(^・ω・^ )","emotion": "cute","keywords": ["cat"]},
  {"text": "(=^-ω-^=)","emotion": "cute","keywords": ["cat"]},
  {"text": "b(=^‥^=)o","emotion": "cute","keywords": ["cat"]},
  {"text": "(.=^・ェ・^=)","emotion": "cute","keywords": ["cat"]},
  {"text": "（=´∇｀=）","emotion": "cute","keywords": ["cat"]},
  {"text": "|-o-|","emotion": "proud","keywords": ["tie","fighter"]},
  {"text": "ヽ(·̿̿Ĺ̯̿̿·̿✿)ﾉ","emotion": "proud","keywords": ["flower","power"]},
  {"text": "✲´*。.❄¨¯`*✲。❄。*。","emotion": "proud","keywords": ["snowing"]},
  {"text": "ᕙ(⇀‸↼‶)ᕗ","emotion": "proud","keywords": ["flex"]},
  {"text": "༼ つ ▀̿_▀̿ ༽つ","emotion": "proud","keywords": ["it's","cool","bro"]},
  {"text": "＼\\ ٩( ᐛ )و /／","emotion": "proud","keywords": ["epic","win"]},
  {"text": "V(-.o)V","emotion": "proud","keywords": ["victory!"]},
  {"text": "(☞ﾟ∀ﾟ)☞","emotion": "proud","keywords": ["this","guy"]},
  {"text": "(。^_・)ノ","emotion": "proud","keywords": ["wave","wink"]},
  {"text": "~(＾◇^)/","emotion": "proud","keywords": ["wave","wink"]},
  {"text": "(･ｪ-)","emotion": "proud","keywords": ["wink"]},
  {"text": "(－ｏ⌒)","emotion": "proud","keywords": ["wink"]},
  {"text": "（＾＿－）","emotion": "proud","keywords": ["wink"]},
  {"text": "(^_-)","emotion": "proud","keywords": ["wink"]},
  {"text": "（＾_-）","emotion": "proud","keywords": ["wink"]},
  {"text": "（＾＿－）≡★","emotion": "proud","keywords": ["wink"]},
  {"text": "（＾＿・）","emotion": "proud","keywords": ["wink"]},
  {"text": "（＾＿−）","emotion": "proud","keywords": ["wink"]},
  {"text": "(^_−)☆","emotion": "proud","keywords": ["wink"]},
  {"text": "(⌒.−)＝★","emotion": "proud","keywords": ["wink"]},
  {"text": "(o‿∩)","emotion": "proud","keywords": ["wink"]},
  {"text": "＼（^０＾）／","emotion": "proud","keywords": ["wink"]},
  {"text": "๏[-ิ_•ิ]๏","emotion": "proud","keywords": ["wink","animals","monkey"]},
  {"text": "☆～（ゝ。∂）","emotion": "proud","keywords": ["wink"]},
  {"text": "n_n","emotion": "joy","keywords": ["joy"]},
  {"text": "( ^​_^）o自自o（^_​^ )","emotion": "joy","keywords": ["cheers"]},
  {"text": "─=≡Σ((( つ•̀ω•́)つLET’SGO!","emotion": "joy","keywords": ["go","hangout","exciting"]},
  {"text": "٩(๑❛ᴗ❛๑)۶","emotion": "joy","keywords": ["cheer"]},
  {"text": "✺◟(∗❛ัᴗ❛ั∗)◞✺","emotion": "joy","keywords": ["cheer"]},
  {"text": "＼＼\\(۶•̀ᴗ•́)۶//／／","emotion": "joy","keywords": ["cheer"]},
  {"text": "(╯°□°）╯︵ ┻━┻","emotion": "angry","keywords": ["table","flip","anger","angry"]},
  {"text": "(づ ò ___ ó )づ ┻━┻","emotion": "angry","keywords": ["table","flip","lesson","take that","anger","angry"]},
  {"text": "┻━┻ ︵ ლ(⌒-⌒ლ)","emotion": "angry","keywords": ["happily","happy","jolly","flip","tables"]},
  {"text": "(ಠ_ಠ)┌∩┐","emotion": "angry","keywords": ["flip","angry","off"]},
  {"text": "ლ(ಠ益ಠ)ლ","emotion": "angry","keywords": ["rage","face"]},
  {"text": "ʕノ•ᴥ•ʔノ ︵ ┻━┻","emotion": "angry","keywords": ["bear","flip","table"]},
  {"text": "┬─┬ ノʕ•ᴥ•ノʔ","emotion": "angry","keywords": ["bear","replacing","table"]},
  {"text": "ʕつಠᴥಠʔつ ︵ ┻━┻","emotion": "angry","keywords": ["disapproving","bear","with","outstretched","arms","flipping"]},
  {"text": "＼＼\\\\٩(๑`^´๑)۶//／／","emotion": "angry","keywords": ["mega","rage"]},
  {"text": "(ヘ･_･)ヘ┳━┳","emotion": "angry","keywords": ["fix","table"]},
  {"text": "¯\\_| ಠ ∧ ಠ |_/¯","emotion": "angry","keywords": ["angry","shrug"]},
  {"text": "(╯°□°）╯︵ ɥsɐpoן","emotion": "angry","keywords": ["lodash","flip"]},
  {"text": "┻━┻︵ \\(°□°)/ ︵ ┻━┻","emotion": "angry","keywords": ["flip","all","tables"]},
  {"text": "(⋟﹏⋞)","emotion": "angry","keywords": ["angry","face"]},
  {"text": "(ง︡-︠)ง","emotion": "angry","keywords": ["fight","me"]},
  {"text": "┏━┓ ︵ /(^.^/)","emotion": "angry","keywords": ["put","table","back"]},
  {"text": "(ↀДↀ)⁼³₌₃","emotion": "angry","keywords": ["cat","cute","pet","angry"]},
  {"text": "(｀⌒*)O-(｀⌒´Q)","emotion": "angry","keywords": ["quarrel","punch_in_face","angry","beat","unhappy"]},
  {"text": "(ﾒ￣▽￣)︻┳═一","emotion": "angry","keywords": ["shooting","weapon","fight","war","gun"]},
  {"text": "(┛✧Д✧))┛彡┻━┻","emotion": "angry","keywords": ["table flip","angry","what?!","shocked"]},
  {"text": "(ノಠ益ಠ)ノ彡┻━┻","emotion": "angry","keywords": ["table flip","angry","what?!","shocked"]},
  {"text": "p(●｀□´●)q","emotion": "angry","keywords": ["thumb_down","angry","unhappy"]},
  {"text": "┬──┬◡ﾉ(° -°ﾉ)","emotion": "angry","keywords": ["table flip"]},
  {"text": "(╯°Д°）╯︵/(.□ . \\)","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノಠ ∩ಠ)ノ彡( \\o°o)\\","emotion": "angry","keywords": ["table flip"]},
  {"text": "(╯°□°)╯︵ ʞooqǝɔɐℲ","emotion": "angry","keywords": ["table flip"]},
  {"text": "ノ┬─┬ノ ︵ ( \\o°o)\\","emotion": "angry","keywords": ["table flip"]},
  {"text": "/( .□.)\\ ︵╰(゜益゜)╯︵ /(.□. /)","emotion": "angry","keywords": ["table flip"]},
  {"text": "(/¯◡ ‿ ◡)/¯ ~ ┻━┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "( ｀o)ﾉﾉ ┫","emotion": "angry","keywords": ["table flip"]},
  {"text": "( ﾉo|o)ﾉ ┫｡ﾟ:.:","emotion": "angry","keywords": ["table flip"]},
  {"text": "（；－－）ノノ ┫：・゜’","emotion": "angry","keywords": ["table flip"]},
  {"text": "(/-o-)/ ⌒ ┤","emotion": "angry","keywords": ["table flip"]},
  {"text": "(/｀ο´)/ ⌒ ┫:’ﾟ:｡･,. 。゜","emotion": "angry","keywords": ["table flip"]},
  {"text": "（/＞□＜）/亠亠","emotion": "angry","keywords": ["table flip"]},
  {"text": "(/ToT)/ ~┻┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(/ToT)/_┫・..","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ ﾟДﾟ)ノ ＝＝＝＝ ┻━━┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-_-)ノ ~┻━┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-_-)ノ ~┻━┻ (/o＼)","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ﾉ-_-)ﾉ ~┻━┻ ☆`","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ－＿－）ノ ┫〝〟∵","emotion": "angry","keywords": ["table flip"]},
  {"text": "（ノ－＿－）ノ・・・~~~┻┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-_-)ノ・・・~~┻━┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "（ノ－＿－）ノ･･･~┻┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-_-)ノ~┻━┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-。-）ノ┻━┻☆( ^)","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-0-)ノ ┫∵：．","emotion": "angry","keywords": ["table flip"]},
  {"text": "（ノ－ｏ－）ノ ”″┻━┻☆（>○<）","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ﾉ-ｏ-)ﾉ ~┫：・’.：：・","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-o-)ノ⌒┳ ┫┻┣","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ-o-)ノ┸┸)`3゜)・;’.","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ﾉ；；)ﾉ~┻━┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ；o；)ノ ┫:･’.::･┻┻:･’.::･","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ；ω；)ノ ┫:･’.::･┻┻:･’.::･","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ﾉ*’‐’)ﾉ ﾐ ┸┸","emotion": "angry","keywords": ["table flip"]},
  {"text": "（ノ｀_´）ﾉ~~┴┴","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ノ｀´）ノミ┻┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "ノToT)ノ ~┻┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "(ﾉ｀□´)ﾉ⌒┻━┻","emotion": "angry","keywords": ["table flip"]},
  {"text": "( -_-)旦~","emotion": "sleepy","keywords": ["sleepy","coffee"]},
  {"text": "(´-ω-)´_ _)´-ω-)´_ _)zZZ","emotion": "sleepy","keywords": ["good night","night","sleepy"]},
  {"text": "（-＾〇＾-）","emotion": "sleepy","keywords": ["happy","sleep"]},
  {"text": "（;≧皿≦）","emotion": "sleepy","keywords": ["angry","sleep"]},
  {"text": "＿ﾉ乙(､ﾝ､)_","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(´〜｀*) zzz","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(ι´Д｀)ﾉ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "_(：3 」∠ )_","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "_(┐「ε:)_","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ꍞ(¦ 3[▓▓]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ꍞ(:˒[▓︎▓︎]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(:ᘌꇤ[￣]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(:⁍ꇤ[▓︎▓︎]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(❁ᴗ͈ ˬ ᴗ͈)ᶻᶻᶻ✧","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "⑅ᵕ༚ᵕ˖˚☽","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "- =͟͟͞͞ (¦3[▓▓])","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "( -_-)>c[_]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(_ _)ヾ(‘ロ‘)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(-_-) zzz","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(-ｪ-)｡o","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(;´ρ`)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(:3[▓▓▓▓▓▓▓▓]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(。-ω-)zzz","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "₍₍ ᕕ( ･᷄ὢ･᷅ )ᕗ⁾⁾","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "₍₍ ᕕ(´ ω` )ᕗ⁾⁾","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "（)´д`(）","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(*-ω-)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(*´ο`*)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(´～`)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "（´□｀川）","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(o´Д`)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(ᴗ˳ᴗ)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(ᵕ≀ ̠ᵕ )","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "［(－－)］zzz","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "【:εω","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "＼（´Ｏ｀）／","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "＼(o￣∇￣o)/","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "˓(¦:ɝ[▓▓]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "∑(￣□￣)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ヾ(。￣□￣)ﾂ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ヾ(￣□￣;)ﾉ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ヾ(￣0￣； )ノ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ƪ(‾￣o￣”)ʃ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ƪ(΄◞ิ۝◟ิ‵)ʃ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(:˒[￣]","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(∪｡∪)｡｡｡zzz","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(▰˘o˘▰)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ε-(´・｀)","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "Σ(￣。￣ノ)ノ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(≚ᄌ≚)ƶƵ","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "(-ι_- )))。。。","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "٩(´Д` ;)۶:.*","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "٩(ˊᗜˋ*)و","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "*｡٩(ˊωˋ*)و✧*｡","emotion": "sleepy","keywords": ["sleep"]},
  {"text": "ᕕ( ᐛ )ᕗ","emotion": "chic","keywords": ["haters","gonna","hate","walk"]},
  {"text": "╭∩╮(Ο_Ο)╭∩╮","emotion": "chic","keywords": ["don","fuller"]},
  {"text": "(•_•)>⌐■-■ (⌐■_■)","emotion": "chic","keywords": ["sunglasses"]},
  {"text": "ᒡ◯ᵔ◯ᒢ","emotion": "chic","keywords": ["glasses"]},
  {"text": "┐(￣∀￣)┌","emotion": "chic","keywords": ["indifference","apathy","insensitivity","disdain"]},
  {"text": "(ﾉ≧∀≦)ﾉ ‥…━━━★","emotion": "chic","keywords": ["majic","star","shooting","biu-biu"]},
  {"text": "╮(─▽─)╭","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "٩(-̮̮̃-̃)۶","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "┗┐ヽ(′Д、`*)ﾉ┌┛","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヽ( ´¬`)ノ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "┗┃・ ■ ・┃┛","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヾ(´A｀)ノﾟ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヽ（・＿・；)ノ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヽ( ￣д￣;)ノ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "＼（〇_ｏ）／","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "＼(;´□｀)/","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヾ(*´ー`)ノ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヽ(‘ー`)ノ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヽ(ー_ー )ノ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヽ(´～｀；）","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "┐(‘～`；)┌","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "ヽ（*ω。）ノ","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "(;´・`)>","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "（＾～＾）","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "٩(-̮̮̃•̃)۶","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "┐(￣ー￣)┌","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "t(ツ)_/¯","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "┐(￣ヮ￣)┌","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "╰( ´◔ ω ◔ `)╯","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "╮(╯▽╰)╭","emotion": "chic","keywords": ["whatever","shrug"]},
  {"text": "o(´^｀)o","emotion": "chic","keywords": ["confused","smug"]},
  {"text": "ー(￣～￣)ξ","emotion": "chic","keywords": ["smug"]},
  {"text": "(((￣へ￣井)","emotion": "chic","keywords": ["smug"]},
  {"text": "(`へ´*)ノ","emotion": "chic","keywords": ["smug"]},
  {"text": "(￣^￣)","emotion": "chic","keywords": ["smug"]},
  {"text": "（￣へ￣）","emotion": "chic","keywords": ["smug"]},
  {"text": "（￣～￣;）","emotion": "chic","keywords": ["smug"]},
  {"text": "(￣ェ￣;)","emotion": "chic","keywords": ["smug"]},
  {"text": "(-、-)","emotion": "chic","keywords": ["smug"]},
  {"text": "( ；｀ヘ´)","emotion": "chic","keywords": ["smug"]},
  {"text": "(￣ω￣;)","emotion": "chic","keywords": ["smug"]},
  {"text": "（｀＾´）ノ","emotion": "chic","keywords": ["smug"]},
  {"text": "<(￣︶￣)>","emotion": "chic","keywords": ["smug"]},
  {"text": "¯\\_ಠ_ಠ_/¯","emotion": "chic","keywords": ["whatever","stare"]},
  {"text": "( ⚆ _ ⚆ )","emotion": "chic","keywords": ["stare"]},
  {"text": "(〠_〠)","emotion": "chic","keywords": ["stare"]},
  {"text": "(◕〝◕)","emotion": "chic","keywords": ["stare"]},
  {"text": "¯\\_(⌣̯̀⌣́)_/¯","emotion": "chic","keywords": ["whatever"]},
  {"text": "(• ε •)","emotion": "chic","keywords": ["stare"]},
  {"text": "┌( ಠ_ಠ)┘","emotion": "chic","keywords": ["stare"]},
  {"text": "┐(´-｀)┌","emotion": "chic","keywords": ["whatever"]},
  {"text": "┐( ˘_˘)┌","emotion": "chic","keywords": ["whatever"]},
  {"text": "¯\\_(シ)_/¯","emotion": "chic","keywords": ["whatever"]},
  {"text": "¯\\(º_o)/¯","emotion": "chic","keywords": ["whatever"]},
  {"text": "(⊙＿⊙')","emotion": "chic","keywords": ["stare"]},
  {"text": "(•̯͡.•̯͡)‎​","emotion": "chic","keywords": ["stare"]},
  {"text": "\\m/ (>.<) \\m/","emotion": "love","keywords": ["rock","on"]},
  {"text": "█▬█ █▄█ █▬█ █▄█","emotion": "love","keywords": ["hu","hu"]},
  {"text": "ʕつ•ᴥ•ʔつ⌐■-■","emotion": "love","keywords": ["bear","putting","on","glasses"]},
  {"text": "／人 ⌒ ‿‿ ⌒ 人＼","emotion": "love","keywords": ["hugme"]},
  {"text": "ᵛᵉᵧₒᵤᶫᵒᵛᵉᵧₒᵤ ᶫᵒᵛᵉᵧₒᵤ","emotion": "love","keywords": ["love","you"]},
  {"text": "(つ◉益◉)つ","emotion": "love","keywords": ["angry","hug"]},
  {"text": "/╲/\\༼ *ಠ 益 ಠ* ༽/\\╱\\","emotion": "love","keywords": ["man","spider"]},
  {"text": "(｡-_-｡ )人( ｡-_-｡)","emotion": "love","keywords": ["love"]},
  {"text": "(っ◕‿◕)っ","emotion": "love","keywords": ["hugs"]},
  {"text": "ᗧ···ᗣ···ᗣ··","emotion": "love","keywords": ["pac","man"]},
  {"text": "(づ ￣ ³￣)づ","emotion": "love","keywords": ["kisses"]},
  {"text": "(づ🌺￣ ³￣)づ","emotion": "love","keywords": ["kisses","cute","flower","girl"]},
  {"text": "(✿ ♥‿♥)","emotion": "love","keywords": ["love","like","loving eyes","smile"]},
  {"text": "♥(ˆ⌣ˆԅ)","emotion": "love","keywords": ["love","like","love left","smile"]},
  {"text": "(*˘︶˘*).｡.:*♡","emotion": "love","keywords": ["smile","joy","heart","love","right heart"]},
  {"text": "(ી(΄◞ิ౪◟ิ‵)ʃ)♥","emotion": "love","keywords": ["happy","love"]},
  {"text": "( c//”-}{-*\\x)","emotion": "love","keywords": ["love","kiss"]},
  {"text": "☆⌒ヽ(*'､^*)chu","emotion": "love","keywords": ["kiss","chu","love","affection","shy"]},
  {"text": "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)","emotion": "love","keywords": ["shy","blush","love"]},
  {"text": "HUG FOR YOU~╰(*´︶`*)╯(´・ω・｀)","emotion": "love","keywords": ["hug","hug you","sweet","comfort","love"]},
  {"text": "♡(㋭ ਊ ㋲)♡","emotion": "love","keywords": ["bird","love"]},
  {"text": "(∿°○°)∿ ︵ ǝʌol","emotion": "love","keywords": ["table flip","love"]},
  {"text": "σ(≧ε≦ｏ)","emotion": "love","keywords": ["excited","kiss"]},
  {"text": "٩(๑ơలơ)۶♡","emotion": "love","keywords": ["excited","love"]},
  {"text": "˚‧*♡ॢ˃̶̤̀◡˂̶̤́♡ॢ*‧˚","emotion": "love","keywords": ["excited","love"]},
  {"text": "٩(ó｡ò۶ ♡)))♬","emotion": "love","keywords": ["excited","love","music"]},
  {"text": "⊂((・▽・))⊃","emotion": "love","keywords": ["happy","hug"]},
  {"text": "d=(´▽｀)=b","emotion": "love","keywords": ["happy","hug"]},
  {"text": "ლ(́◉◞౪◟◉‵ლ)","emotion": "love","keywords": ["happy","love","hug"]},
  {"text": "(‘∀’●)♡","emotion": "love","keywords": ["love"]},
  {"text": "(*´∀｀*人*´∀｀*)","emotion": "love","keywords": ["love"]},
  {"text": "(/^-^(^ ^*)/","emotion": "love","keywords": ["love"]},
  {"text": "(´ ▽｀).。ｏ♡","emotion": "love","keywords": ["love"]},
  {"text": "(´∀｀)♡","emotion": "love","keywords": ["love","happy"]},
  {"text": "ヽ(愛´∀｀愛)ノ","emotion": "love","keywords": ["love"]},
  {"text": "(●♡∀♡)","emotion": "love","keywords": ["love"]},
  {"text": "( ˘ ³˘)♥","emotion": "love","keywords": ["love","kiss"]},
  {"text": "( ˘ ³˘)❤","emotion": "love","keywords": ["love","kiss"]},
  {"text": "( ⋆•ิ ᴈ-ิ(ᵕ❥ ᵕ⁎ ॢ)","emotion": "love","keywords": ["love","kiss"]},
  {"text": "(・_・)❤(-_-)","emotion": "love","keywords": ["love"]},
  {"text": "(｡・//ε//・｡)","emotion": "love","keywords": ["love","kiss"]},
  {"text": "(｡･ω･｡)ﾉ♡","emotion": "love","keywords": ["love","animals","pig"]},
  {"text": "(｡’▽’｡)♡","emotion": "love","keywords": ["love"]},
  {"text": "（。ˇ ⊖ˇ）♡","emotion": "love","keywords": ["love"]},
  {"text": "(｡♥‿♥｡)","emotion": "love","keywords": ["love"]},
  {"text": "(* ˘⌣˘)◞[_]♥[_]ヽ(•‿• )","emotion": "love","keywords": ["love"]},
  {"text": "（*´▽｀*）","emotion": "love","keywords": ["love","music","happy"]},
  {"text": "（*＾3＾）/～♡","emotion": "love","keywords": ["love","kiss"]},
  {"text": "（〃・ω・〃）","emotion": "love","keywords": ["love"]},
  {"text": "（´・｀ ）♡","emotion": "love","keywords": ["love","kiss"]},
  {"text": "(´▽`ʃƪ)♡","emotion": "love","keywords": ["love"]},
  {"text": "(´ε｀ )♡","emotion": "love","keywords": ["love","kiss"]},
  {"text": "（´ω｀♡%）","emotion": "love","keywords": ["love"]},
  {"text": "(˘▼˘>ԅ( ˘⌣ƪ)","emotion": "love","keywords": ["love"]},
  {"text": "(ˆˇˆ)-c<˘ˑ˘)","emotion": "love","keywords": ["love"]},
  {"text": "(>’o’)> ♥ <(‘o’<)","emotion": "love","keywords": ["love"]},
  {"text": "(>^_^)><(^o^<)","emotion": "love","keywords": ["love","hug"]},
  {"text": "(∩˃o˂∩)♡","emotion": "love","keywords": ["love"]},
  {"text": "(◍•ᴗ•◍)❤","emotion": "love","keywords": ["love"]},
  {"text": "(♥ó㉨ò)ﾉ♡","emotion": "love","keywords": ["love","bear"]},
  {"text": "(¡ ¡)","emotion": "lol","keywords": ["binding","of","isaac"]},
  {"text": "ʕಠಿᴥಠʔ ಠಿ_ಠ ᶘಠಿᴥಠᶅ","emotion": "lol","keywords": ["council","of","doubt"]},
  {"text": "ʕಠᴥಠʔ ಠ_ಠ ᶘಠᴥಠᶅ","emotion": "lol","keywords": ["council","of","disapproval"]},
  {"text": "(/◕ヮ◕)/ (^o^) (✿◠‿◠)","emotion": "lol","keywords": ["council","of","approval"]},
  {"text": "(＾▽＾)","emotion": "lol","keywords": ["laughing"]},
  {"text": "(´◑ω◐`)","emotion": "lol","keywords": ["awkward","funny","weird","idiot"]},
  {"text": "∗˚(* ˃̤൬˂̤ *)˚∗","emotion": "lol","keywords": ["excited","laugh"]},
  {"text": "（ ´∀｀）","emotion": "lol","keywords": ["happy","laugh"]},
  {"text": "（＞ｙ＜）","emotion": "lol","keywords": ["happy","laugh"]},
  {"text": "（＾ｖ＾）","emotion": "lol","keywords": ["happy","laugh"]},
  {"text": "(ノ＞▽＜。)ノ","emotion": "lol","keywords": ["happy","laugh"]},
  {"text": "ヾ(＠⌒ー⌒＠)ノ","emotion": "lol","keywords": ["happy","wave","fun"]},
  {"text": "ლ(╹◡╹ლ)","emotion": "lol","keywords": ["happy","fun"]},
  {"text": "ʘ‿ʘ","emotion": "lol","keywords": ["happy","fun"]},
  {"text": "“ψ(｀∇´)ψ","emotion": "lol","keywords": ["evil","laugh"]},
  {"text": "ヾ(⌐■_■)ノ♪","emotion": "lol","keywords": ["dance","fun"]},
  {"text": "ヘ(^_^ヘ)","emotion": "lol","keywords": ["dance","fun","happy"]},
  {"text": "(*´艸`*)","emotion": "lol","keywords": ["laugh"]},
  {"text": "(●´艸`)","emotion": "lol","keywords": ["laugh"]},
  {"text": "｡ﾟ(TヮT)ﾟ｡","emotion": "lol","keywords": ["laugh"]},
  {"text": "( ´艸｀)","emotion": "lol","keywords": ["laugh"]},
  {"text": "（・∀・）","emotion": "lol","keywords": ["laugh"]},
  {"text": "(；-◞౪◟-)","emotion": "lol","keywords": ["laugh"]},
  {"text": "(｡ >艸<)","emotion": "lol","keywords": ["laugh"]},
  {"text": "(*・艸・)","emotion": "lol","keywords": ["laugh"]},
  {"text": "(*≧▽≦)ﾉｼ))","emotion": "lol","keywords": ["laugh"]},
  {"text": "(*≧艸≦)","emotion": "lol","keywords": ["laugh"]},
  {"text": "（⌒▽⌒）","emotion": "lol","keywords": ["laugh"]},
  {"text": "(◎ヮ◎)","emotion": "lol","keywords": ["laugh"]},
  {"text": "ʕ̡̢̡̡̢̡̡̢♡ᵒ̴̷͈艸ᵒ̴̷͈॰ʔ̢̡̢̢̡̢̢̡̢✧","emotion": "lol","keywords": ["laugh"]},
  {"text": "Σ (੭ु ຶਊ ຶ)੭ु⁾⁾","emotion": "lol","keywords": ["laugh"]},
  {"text": "(ᗒᗜᗕ)՛̵̖","emotion": "lol","keywords": ["laugh"]},
  {"text": "(* ˚᷄ 艸 ˚᷅ *)","emotion": "lol","keywords": ["laugh"]},
  {"text": "∗˚೫˳(●ᴖ͙̏ᴗॢᴖ͙̋●)˳೫˚∗","emotion": "lol","keywords": ["laugh"]},
  {"text": "(੭ु റ̆ ˒̫̮ റ̥)੭ु⁾⁾","emotion": "lol","keywords": ["laugh"]},
  {"text": "(˃̴̀ᄇॢ˂̴́ ∗)","emotion": "lol","keywords": ["laugh","think"]},
  {"text": "d(-_^)","emotion": "lol","keywords": ["wink","fun"]},
  {"text": "\\(-ㅂ-)/ ♥ ♥ ♥","emotion": "lol","keywords": ["fun","love"]},
  {"text": "Ɛ:[,,_,,]=~","emotion": "lol","keywords": ["animals","cat","fun"]},
  {"text": "๏◡๏","emotion": "lol","keywords": ["fun"]},
  {"text": "\\m/...(>.<)…\\m/","emotion": "lol","keywords": ["fun","music"]},
  {"text": "（ ＾）／占~~~~~","emotion": "lol","keywords": ["fun"]},
  {"text": "(／_^)／ ● ＼(^_＼)","emotion": "lol","keywords": ["fun"]},
  {"text": "(／o^)/ °⊥ ＼(^o＼)","emotion": "lol","keywords": ["fun"]},
  {"text": "ヽ｀、ヽ｀ヽ(*￣o￣*)♩♫♪ヽ｀、ヽ｀","emotion": "lol","keywords": ["fun","happy"]},
  {"text": "（*＾＾）/~~~~◎","emotion": "lol","keywords": ["fun"]},
  {"text": "(*・_・)ノ⌒*`*`*","emotion": "lol","keywords": ["fun"]},
  {"text": "◉‿◉","emotion": "lol","keywords": ["fun","happy"]},
  {"text": "¯\\_◉‿◉_/¯","emotion": "lol","keywords": ["fun","happy","whatever"]},
  {"text": "|ʘ‿ʘ)╯","emotion": "lol","keywords": ["fun","wave"]},
  {"text": "(~^.^)~","emotion": "lol","keywords": ["fun"]},
  {"text": "ʕ•̫͡•ʕ*̫͡*ʕ•͓͡•ʔ-̫͡-ʕ•̫͡•ʔ*̫͡*ʔ","emotion": "lol","keywords": ["animals","bear","fun"]},
  {"text": "(●°u°●)​ 」","emotion": "lol","keywords": ["fun","happy","wave"]},
  {"text": "~=[,,_,,]:3","emotion": "lol","keywords": ["animals","cat","fun"]},
  {"text": "| (• ◡•)| (❍ᴥ❍ʋ)","emotion": "lol","keywords": ["fun","happy"]},
  {"text": "└[∵┌]└[ ∵ ]┘[┐∵]┘","emotion": "lol","keywords": ["fun","happy"]},
  {"text": "(^__^)v","emotion": "lol","keywords": ["fun","happy"]},
  {"text": "（。々°）","emotion": "lol","keywords": ["fun"]},
  {"text": "（°々。）","emotion": "lol","keywords": ["fun"]},
  {"text": "(◐‿◑)﻿","emotion": "lol","keywords": ["crazy","fun","happy"]},
  {"text": "ₒ₍₊˒₃˓₎ₒ▁▂▃▅▆▓▒░✩⃛","emotion": "hi","keywords": ["blow","me"]},
  {"text": "(⌒ω⌒)ﾉ","emotion": "hi","keywords": ["greeting","hello","morning","what's up","hand up","smile"]},
  {"text": "(￣(ｴ)￣)ﾉ","emotion": "hi","keywords": ["bear","wave"]},
  {"text": "ヾ(´(ｴ)｀ﾉﾞ","emotion": "hi","keywords": ["bear","wave"]},
  {"text": "“(`(エ)´)ノ","emotion": "hi","keywords": ["bear","wave"]},
  {"text": "ヘ(゜Д、゜)ノ","emotion": "hi","keywords": ["crazy","wave"]},
  {"text": "ヘ(°◇、°)ノ","emotion": "hi","keywords": ["crazy","wave"]},
  {"text": "(￣(oo)￣)ﾉ","emotion": "hi","keywords": ["pig","wave"]},
  {"text": "(,, ･∀･)ﾉ゛","emotion": "hi","keywords": ["wave"]},
  {"text": "(;-_-)/","emotion": "hi","keywords": ["wave","surrender"]},
  {"text": "(｡･ω･)ﾉﾞ","emotion": "hi","keywords": ["wave"]},
  {"text": "(。･д･)ﾉﾞ","emotion": "hi","keywords": ["wave"]},
  {"text": "(｡´∀｀)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "(/・0・)","emotion": "hi","keywords": ["wave"]},
  {"text": "(´・ω・)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "(￣∠ ￣ )ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "(=ﾟωﾟ)ノ","emotion": "hi","keywords": ["wave"]},
  {"text": "(ノ^∇^)","emotion": "hi","keywords": ["wave"]},
  {"text": "＼(°o°；）","emotion": "hi","keywords": ["wave"]},
  {"text": "ヽ(´･ω･`)､","emotion": "hi","keywords": ["wave"]},
  {"text": "( ・_・)ノ","emotion": "hi","keywords": ["wave"]},
  {"text": "( ･ω･)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "( ^_^)／","emotion": "hi","keywords": ["wave"]},
  {"text": "（ ゜ρ゜)ノ","emotion": "hi","keywords": ["wave"]},
  {"text": "( ﾟ▽ﾟ)/","emotion": "hi","keywords": ["wave"]},
  {"text": "(;-_-)ノ","emotion": "hi","keywords": ["wave","surrender"]},
  {"text": "(。-ω-)ﾉ","emotion": "hi","keywords": ["wave","surrender"]},
  {"text": "(*^･ｪ･)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "(*＾▽＾)／","emotion": "hi","keywords": ["wave"]},
  {"text": "(*￣Ｏ￣)ノ","emotion": "hi","keywords": ["wave"]},
  {"text": "(^ Q ^)/","emotion": "hi","keywords": ["wave"]},
  {"text": "(^-^*)/","emotion": "hi","keywords": ["wave"]},
  {"text": "(^o^)/","emotion": "hi","keywords": ["wave"]},
  {"text": "(￣▽￣)ノ","emotion": "hi","keywords": ["wave"]},
  {"text": "(=ﾟωﾟ)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "(o・・o)/","emotion": "hi","keywords": ["wave"]},
  {"text": "(o´ω`o)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "(ﾉ´∀｀*)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "＼( ･_･)","emotion": "hi","keywords": ["wave"]},
  {"text": "＼(-_- )","emotion": "hi","keywords": ["wave"]},
  {"text": "＼(-o- )","emotion": "hi","keywords": ["wave","surrender"]},
  {"text": "＼（＾∀＾）メ（＾∀＾）ノ","emotion": "hi","keywords": ["wave"]},
  {"text": "＼(＾▽＾*)","emotion": "hi","keywords": ["wave"]},
  {"text": "＼(￣O￣)","emotion": "hi","keywords": ["wave"]},
  {"text": "~ヾ ＾∇＾","emotion": "hi","keywords": ["wave"]},
  {"text": "~ヾ(＾∇＾)","emotion": "hi","keywords": ["wave"]},
  {"text": "╭(°ﾛ°”)╯","emotion": "hi","keywords": ["wave"]},
  {"text": "ー( ´ ▽ ` )ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ( ‘ – ‘*)","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(-_-;)","emotion": "hi","keywords": ["wave","surrender"]},
  {"text": "ヽ(･∀･)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(･ω･`｡)","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(・ω・ｏ)","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(｡･ω･｡)","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(｡´･_●･`｡)☆","emotion": "hi","keywords": ["wave"]},
  {"text": "ヽ(๏∀๏ )ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(´･ω･｀)","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(´￢｀)ﾉ","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(＾-＾)ノ","emotion": "hi","keywords": ["wave"]},
  {"text": "ヾ(＾∇＾)","emotion": "hi","keywords": ["wave"]},
  {"text": "8)~~~~~ *","emotion": "cry","keywords": ["frog","eating","a","fly"]},
  {"text": "ლ(ಠ_ಠლ)","emotion": "cry","keywords": ["y","u","no"]},
  {"text": "(╯^□^)╯︵ ❄☃❄","emotion": "cry","keywords": ["playing","in","snow"]},
  {"text": "੨( ･᷄ ︵･᷅ )ｼ","emotion": "cry","keywords": ["cry","depressed","unhappy"]},
  {"text": "꒰๑•̥﹏•̥๑꒱","emotion": "cry","keywords": ["cry","vertical tears","failed","unhappy"]},
  {"text": "(ノ_<。)ヾ(´▽｀)","emotion": "cry","keywords": ["cry","kindness","affinity","compassion"]},
  {"text": "(╥﹏╥)","emotion": "cry","keywords": ["crying"]},
  {"text": "＼(*T▽T*)／","emotion": "cry","keywords": ["excited","happy","cry"]},
  {"text": "＼（Ｔ∇Ｔ）／","emotion": "cry","keywords": ["excited","happy","cry"]},
  {"text": "ヽ(；▽；)ノ","emotion": "cry","keywords": ["excited","happy","cry"]},
  {"text": "ヾ(＠† ▽ †＠）ノ","emotion": "cry","keywords": ["excited","happy","cry"]},
  {"text": "(٭°̧̧̧ω°̧̧̧٭)","emotion": "cry","keywords": ["excited","cry"]},
  {"text": "＼（＠；◇；＠）／","emotion": "cry","keywords": ["happy","cry"]},
  {"text": "(o;TωT)o","emotion": "cry","keywords": ["happy","cry"]},
  {"text": "ͼ(ݓ_ݓ)ͽ","emotion": "cry","keywords": ["angry","cry"]},
  {"text": "（ ; ; ）","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(T＿T)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "（ ＴДＴ）","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(Ｔ▽Ｔ)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(T_T)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "((T.T； )","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(； T.T))","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "（；へ：）","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(ノД`)・゜・。","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "｡：ﾟ(｡ﾉω＼｡)ﾟ･｡","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(┳Д┳)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(´；д；`)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(*´；ェ；`*)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "｡･ﾟﾟ･(>д<)･ﾟﾟ･｡","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(。┰ω┰。)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "（ｉДｉ）","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(´；ω；`)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "。ﾟ(ﾟﾉД｀ﾟ)ﾟ｡","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "( p_q)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(个_个)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "｡゜(｀Д´)゜｡","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(/□＼*)・゜","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "((o(;△;)o))","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(ㄒoㄒ)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "o(；△；)o","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(;*△*;)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "╥﹏╥","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(´°̥̥̥̥̥̥̥̥ω°̥̥̥̥̥̥̥̥｀)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "(╥_╥)","emotion": "cry","keywords": ["sad","cry"]},
  {"text": "⁽⁽ƈ ͡ (ु ˲̥̥̥́ ˱̥̥̥̀) ु⁾⁾","emotion": "cry","keywords": ["hurt","cry"]},
  {"text": "( °̥̥̥̥̥̥̥̥˟°̥̥̥̥̥̥̥̥ )","emotion": "cry","keywords": ["rabbit","cry"]},
  {"text": "・゜・(ノД`)","emotion": "cry","keywords": ["cry"]},
  {"text": ".・゜゜・（／。＼）・゜゜・．","emotion": "cry","keywords": ["cry"]},
  {"text": "(oT-T)尸","emotion": "cry","keywords": ["cry","surrender"]},
  {"text": ".·´¯`(>▂<)´¯`·.","emotion": "cry","keywords": ["cry"]},
  {"text": "｡･ﾟヾ(✦థ ｪ థ)ﾉ｡ﾟ･｡","emotion": "cry","keywords": ["cry"]},
  {"text": "。：゜(；´∩｀；)゜：。","emotion": "cry","keywords": ["cry"]},
  {"text": "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡","emotion": "cry","keywords": ["cry"]},
  {"text": "(-̩̩-̩̩͡_-̩̩-̩̩͡)","emotion": "cry","keywords": ["cry"]},
  {"text": "(/ _ ; )","emotion": "cry","keywords": ["cry","surrender"]},
  {"text": "(´；Д；｀)","emotion": "cry","keywords": ["cry"]},
  {"text": "（πーπ）","emotion": "cry","keywords": ["cry"]},
  {"text": "(இ﹏இ`｡)","emotion": "cry","keywords": ["cry"]},
  {"text": "༼ ༎ຶ ෴ ༎ຶ༽","emotion": "cry","keywords": ["cry","troll"]},
  {"text": "༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽","emotion": "cry","keywords": ["cry","troll"]},
  {"text": "(ง︡’-‘︠)ง","emotion": "shrug","keywords": ["stick","up","your","dukes"]},
  {"text": "٩(͡๏̯͡๏)۶","emotion": "shrug","keywords": ["dunno"]},
  {"text": "༼ つ ◕_◕ ༽つ","emotion": "shrug","keywords": ["gimme","give","reach","take","have"]},
  {"text": "ʅ(°_°)ʃ","emotion": "shrug","keywords": ["octopus","shrug","squid"]},
  {"text": "¯\\_(ツ)_/¯","emotion": "shrug","keywords": ["shrug"]},
  {"text": "(＠_＠)","emotion": "shrug","keywords": ["donno","confused","doubt","question"]},
  {"text": "(´･_･`)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(◎_◎;)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(｀_´)ゞ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(◎-◎；)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(・_・ヾ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(￣(エ)￣)ゞ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(-_-)ゞ゛","emotion": "shrug","keywords": ["confused"]},
  {"text": "(‘◇’)?","emotion": "shrug","keywords": ["confused"]},
  {"text": "ヽ(゜Q。)ノ？","emotion": "shrug","keywords": ["confused"]},
  {"text": "(´｀;) ？","emotion": "shrug","keywords": ["confused"]},
  {"text": "【・ヘ・?】","emotion": "shrug","keywords": ["confused"]},
  {"text": "【・_・?】","emotion": "shrug","keywords": ["confused"]},
  {"text": "( ・◇・)？","emotion": "shrug","keywords": ["confused"]},
  {"text": "(゜-゜)","emotion": "shrug","keywords": ["confused"]},
  {"text": "ヾ(´･ ･｀｡)ノ”","emotion": "shrug","keywords": ["confused"]},
  {"text": "｢(ﾟﾍﾟ)","emotion": "shrug","keywords": ["confused"]},
  {"text": "( ?´_ゝ｀)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(´−｀) ﾝｰ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(」ﾟヘﾟ)」","emotion": "shrug","keywords": ["confused"]},
  {"text": "(•ิ_•ิ)?","emotion": "shrug","keywords": ["confused"]},
  {"text": "「(°ヘ°)","emotion": "shrug","keywords": ["confused"]},
  {"text": "〈(゜。゜)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(゜。゜)","emotion": "shrug","keywords": ["confused"]},
  {"text": "く（＾_・）ゝ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(^～^;)ゞ","emotion": "shrug","keywords": ["confused"]},
  {"text": "щ(ºДºщ)","emotion": "shrug","keywords": ["confused"]},
  {"text": "﴾͡๏̯͡๏﴿","emotion": "shrug","keywords": ["confused"]},
  {"text": "ఠ_ఠ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(●__●)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(ﾟｰﾟ;","emotion": "shrug","keywords": ["confused"]},
  {"text": "(●´ω｀●)ゞ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(＃⌒∇⌒＃)ゞ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(・・。)ゞ","emotion": "shrug","keywords": ["confused"]},
  {"text": "(⊙_☉)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(⊙.☉)7","emotion": "shrug","keywords": ["confused"]},
  {"text": "(」ﾟﾛﾟ)｣","emotion": "shrug","keywords": ["confused"]},
  {"text": "(C_C)","emotion": "shrug","keywords": ["confused"]},
  {"text": "(¬ω¬)","emotion": "shrug","keywords": ["think"]},
  {"text": "( ¬_¬)","emotion": "shrug","keywords": ["think"]},
  {"text": "(∩⌣̀_⌣́)","emotion": "shrug","keywords": ["think"]},
  {"text": "(ʃ⌣́,⌣́ƪ)","emotion": "shrug","keywords": ["think"]},
  {"text": "<(¬＿¬<)","emotion": "shrug","keywords": ["think"]},
  {"text": "(•᷉ुε ू•᷈,)","emotion": "shrug","keywords": ["think"]},
  {"text": "๐छ ੂछ๐","emotion": "shrug","keywords": ["think"]},
  {"text": "눈_눈","emotion": "shrug","keywords": ["think"]},
  {"text": "Σ(-᷅_-᷄๑)","emotion": "shrug","keywords": ["think"]},
  {"text": "(.﹒︣︿﹒︣.)","emotion": "shrug","keywords": ["think"]},
  {"text": "( ･᷄ㅂ･᷅ )","emotion": "shrug","keywords": ["think"]},
  {"text": "( ᵕ́ૢ‧̮ᵕ̀ૢ)‧̊·*","emotion": "shrug","keywords": ["think"]},
  {"text": "(๑•̆૩•̆)","emotion": "shrug","keywords": ["think"]},
  {"text": "(一。一;;）","emotion": "shrug","keywords": ["surrender"]},
  {"text": "( -。-)","emotion": "shrug","keywords": ["surrender"]},
  {"text": "(-_＼)","emotion": "shrug","keywords": ["surrender"]},
  {"text": "(;*´Д`)ﾉ","emotion": "shrug","keywords": ["surrender"]},
  {"text": "(๑˃̵ᴗ˂̵)و","emotion": "surprise","keywords": ["omg","yes"]},
  {"text": "(∩╹□╹∩)","emotion": "surprise","keywords": ["shocked"]},
  {"text": "＼(º □ º l|l)/","emotion": "surprise","keywords": ["afraid","shocked","fear","hands up"]},
  {"text": "∑(O_O;)","emotion": "surprise","keywords": ["surprised","shocked","curious"]},
  {"text": "(＾་།＾)","emotion": "surprise","keywords": ["shocked","nose","blood","sexy","beautiful"]},
  {"text": "( ꒪Д꒪)ノ","emotion": "surprise","keywords": ["surprised"]},
  {"text": "(((( ;°Д°))))","emotion": "surprise","keywords": ["surprised"]},
  {"text": "((((；゜Д゜)))","emotion": "surprise","keywords": ["surprised"]},
  {"text": "（゜◇゜）","emotion": "surprise","keywords": ["surprised"]},
  {"text": "（￣□￣；）","emotion": "surprise","keywords": ["surprised","surrender"]},
  {"text": "∑(O_O；)","emotion": "surprise","keywords": ["surprised"]},
  {"text": "＼(>o<)ノ","emotion": "surprise","keywords": ["surprised"]},
  {"text": "━Σ(ﾟДﾟ|||)━","emotion": "surprise","keywords": ["surprised"]},
  {"text": "Σ(゜ロ゜;)","emotion": "surprise","keywords": ["surprised"]},
  {"text": "Σ(゜゜)","emotion": "surprise","keywords": ["surprised"]},
  {"text": "(*ﾟﾛﾟ)","emotion": "surprise","keywords": ["surprised"]},
  {"text": "щ(゜ロ゜щ)","emotion": "surprise","keywords": ["surprised"]},
  {"text": "(ﾉﾟ0ﾟ)ﾉ~","emotion": "surprise","keywords": ["surprised"]},
  {"text": "⊙▂⊙","emotion": "surprise","keywords": ["surprised"]},
  {"text": "⊙０⊙","emotion": "surprise","keywords": ["surprised"]},
  {"text": "w(°ｏ°)w","emotion": "surprise","keywords": ["surprised"]},
  {"text": "L(・o・)」","emotion": "surprise","keywords": ["surprised"]},
  {"text": "(○o○)","emotion": "surprise","keywords": ["surprised"]},
  {"text": "（・□・；）","emotion": "surprise","keywords": ["surprised"]},
  {"text": "∑(;°Д°)","emotion": "surprise","keywords": ["surprised"]},
  {"text": "(´⊙ω⊙`)！","emotion": "surprise","keywords": ["surprised"]},
  {"text": "\\(*0*)/","emotion": "surprise","keywords": ["surprised"]},
  {"text": "ヽ༼ຈʖ̯ຈ༽ﾉ","emotion": "sad","keywords": ["sad","donger"]},
  {"text": "( ͡° ʖ̯ ͡°)","emotion": "sad","keywords": ["sad","lenny"]},
  {"text": "(；゜○゜)ア","emotion": "sad","keywords": ["point"]},
  {"text": "o(≧∇≦o)","emotion": "sad","keywords": ["exciting","circle hands","happy","joy"]},
  {"text": "(/^▽^)/","emotion": "sad","keywords": ["exciting","right","hands up","happy"]},
  {"text": "(‘A`)","emotion": "sad","keywords": ["sad"]},
  {"text": "(=ↀωↀ=)✧","emotion": "sad","keywords": ["cat","cute","pet"]},
  {"text": "(^_<)〜☆","emotion": "sad","keywords": ["winking","star","cute","trick","joke"]},
  {"text": "｡ﾟ(ﾟ´(00)`ﾟ)ﾟ｡","emotion": "sad","keywords": ["pig","cute","pork"]},
  {"text": "ヽ(≧◡≦)八(o^ ^o)ノ","emotion": "sad","keywords": ["friends","hangout","cheer","together","happy","smile"]},
  {"text": "\\\\\\(۶•̀ᴗ•́)۶//／／","emotion": "sad","keywords": ["happy","cheer","joy","hands up"]},
  {"text": "/ᐠ｡ꞈ｡ᐟ✿\\","emotion": "sad","keywords": ["cat","flower","nya","meow","pet","cute"]},
  {"text": "(✿◕㉨◕)","emotion": "sad","keywords": ["bear","animal","cute","pet","flower"]},
  {"text": "(((o(*ﾟ▽ﾟ*)o)))","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "(★^O^★)","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "＼（＠￣∇￣＠）／","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "＼(^▽^＠)ノ","emotion": "sad","keywords": ["excited","happy","dance"]},
  {"text": "o((*^▽^*))o","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "Ｏ(≧▽≦)Ｏ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "(((＼（＠v＠）／)))","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "(*≧▽≦)","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "(ﾉ´ヮ´)ﾉ*:･ﾟ✧","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "☆*･゜ﾟ･*\\(^O^)/*･゜ﾟ･*☆","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "☆*:.｡. o(≧▽≦)o .｡.:*☆","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヽ(;^o^ヽ)","emotion": "sad","keywords": ["excited","happy","dance"]},
  {"text": "ヾ(＠^∇^＠)ノ","emotion": "sad","keywords": ["excited","happy","dance"]},
  {"text": "ヾ(＠^▽^＠)ﾉ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヾ（＠＾▽＾＠）ノ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヾ(＠゜▽゜＠）ノ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヾ(＠°▽°＠)ﾉ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヽ(*≧ω≦)ﾉ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヽ(*⌒∇⌒*)ﾉ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヽ(^。^)丿","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "ヽ(＾Д＾)ﾉ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "o(〃＾▽＾〃)o","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "o(^▽^)o","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "Ｏ(≧∇≦)Ｏ","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "о(ж＞▽＜)ｙ ☆","emotion": "sad","keywords": ["excited","happy"]},
  {"text": "(●´∀｀●)","emotion": "sad","keywords": ["happy"]},
  {"text": "(｀・ω・´)”","emotion": "sad","keywords": ["happy"]},
  {"text": "(*´・ｖ・)","emotion": "sad","keywords": ["happy"]},
  {"text": "(⌒▽⌒)☆","emotion": "sad","keywords": ["happy"]},
  {"text": "(≧∇≦)/","emotion": "sad","keywords": ["happy","wave"]},
  {"text": "(´∇ﾉ｀*)ノ","emotion": "sad","keywords": ["happy"]},
  {"text": "（・◇・）","emotion": "sad","keywords": ["happy"]},
  {"text": "( ´ ▽ ` )ﾉ","emotion": "sad","keywords": ["happy","wave"]},
  {"text": "（＾_＾）","emotion": "sad","keywords": ["happy"]},
  {"text": "（￣ー￣）","emotion": "sad","keywords": ["happy"]},
  {"text": "(*^▽^*)","emotion": "sad","keywords": ["happy"]},
  {"text": "（’-’*)","emotion": "sad","keywords": ["happy"]},
  {"text": "＼（＾ ＾）／","emotion": "sad","keywords": ["happy"]},
  {"text": "(^～^)","emotion": "sad","keywords": ["happy"]},
  {"text": "(☆^O^☆)","emotion": "sad","keywords": ["happy"]},
  {"text": "(☆^ー^☆)","emotion": "sad","keywords": ["happy"]},
  {"text": "(´ω｀★)","emotion": "sad","keywords": ["happy"]},
  {"text": "*(*´∀｀*)☆","emotion": "sad","keywords": ["happy"]},
  {"text": "ヽ(‘ ∇‘ )ノ","emotion": "sad","keywords": ["happy","crazy"]},
  {"text": "（*＾ワ＾*）","emotion": "sad","keywords": ["happy"]},
  {"text": "(´∀`)","emotion": "sad","keywords": ["happy"]},
  {"text": "(°◇°;)","emotion": "sad","keywords": ["happy"]},
  {"text": "(///∇///✿)","emotion": "flutter","keywords": ["blushing","girl","flower","shy","cute"]},
  {"text": "(⊃‿⊂)","emotion": "shy","keywords": ["hide"]},
  {"text": "|_・)","emotion": "shy","keywords": ["hide"]},
  {"text": "|･ω･｀)","emotion": "shy","keywords": ["hide"]},
  {"text": "｜−・;）","emotion": "shy","keywords": ["hide"]},
  {"text": "|ω・）","emotion": "shy","keywords": ["hide"]},
  {"text": "|ω･)و ̑̑༉","emotion": "shy","keywords": ["hide"]},
  {"text": "( ͒•·̫|","emotion": "shy","keywords": ["hide"]},
  {"text": "┬┴┬┴┤(･_├┬┴┬┴","emotion": "shy","keywords": ["hide"]},
  {"text": "ﾍ(･_|","emotion": "shy","keywords": ["hide"]},
  {"text": "|₋ॢọ̶̶̷̥᷅๑)‧˚⁺","emotion": "shy","keywords": ["hide"]},
  {"text": "川o･-･)ﾉ","emotion": "shy","keywords": ["hide","wave"]},
  {"text": "┻┳|･ω･)","emotion": "shy","keywords": ["hide"]},
  {"text": "┻┳|･ω･)ﾉ","emotion": "shy","keywords": ["hide","wave"]},
  {"text": "(*σᴗσ)(ㅎᴗㅎ ) ｜‸눈;)","emotion": "shy","keywords": ["hide"]},
  {"text": "| ू•ૅω•́)ᵎᵎᵎ","emotion": "shy","keywords": ["hide"]}
];
